---
name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    name: Run code style checks and static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.10

      - name: Apply dependency cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-analysis-${{ hashFiles('setup.py') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pre-commit

      - name: Restore pre-commit hooks from cache
        uses: actions/cache@v3
        id: restore-pre-commit-hooks
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-

      - name: Install pre-commit hooks
        if: steps.restore-pre-commit-hooks.outputs.cache-hit != 'true'
        run: |
          pre-commit install-hooks

      - name: Lint
        run: |
          pre-commit run --all-files
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.10

      - name: Apply dependency cache
        uses: actions/cache@v3
        id: venv-cache
        with:
          path: ./env/
          key: ${{ runner.os }}-env-5-${{ hashFiles('setup.py') }}
          restore-keys: ${{ runner.os }}-env-5-

      - name: Install dependencies
        run: |
          python -m venv env
          source ./env/bin/activate
          python -m pip install --upgrade pip
          python -m pip install --upgrade -e ".[test]"

      - name: Run pytest
        run: |
          source ./env/bin/activate
          python -m pytest -vvv
